"""add maintenance_requests

Revision ID: 405a20d32df6
Revises: 4f6bf92b0607
Create Date: 2026-07-22 11:43:38.021566

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "405a20d32df6"
down_revision: Union[str, Sequence[str], None] = "4f6bf92b0607"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "maintenance_requests",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("property_id", sa.Uuid(), nullable=False),
        sa.Column("lease_id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "priority",
            sa.Enum("low", "medium", "high", "urgent", name="maintenancepriority"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("open", "in_progress", "resolved", "cancelled", name="maintenancestatus"),
            nullable=False,
        ),
        sa.Column("image_urls", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["lease_id"], ["leases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["property_id"],
            ["properties.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_maintenance_requests_created_by"),
        "maintenance_requests",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_maintenance_requests_lease_id"), "maintenance_requests", ["lease_id"], unique=False
    )
    op.create_index(
        op.f("ix_maintenance_requests_organization_id"),
        "maintenance_requests",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_maintenance_requests_property_id"),
        "maintenance_requests",
        ["property_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_maintenance_requests_property_id"), table_name="maintenance_requests")
    op.drop_index(
        op.f("ix_maintenance_requests_organization_id"), table_name="maintenance_requests"
    )
    op.drop_index(op.f("ix_maintenance_requests_lease_id"), table_name="maintenance_requests")
    op.drop_index(op.f("ix_maintenance_requests_created_by"), table_name="maintenance_requests")
    op.drop_table("maintenance_requests")
    sa.Enum(name="maintenancepriority").drop(op.get_bind())
    sa.Enum(name="maintenancestatus").drop(op.get_bind())
    # ### end Alembic commands ###
