"""add charge reminders

Revision ID: 59285cbffe1c
Revises: 0e07c7d866ed
Create Date: 2026-07-22 14:39:34.946409

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "59285cbffe1c"
down_revision: Union[str, Sequence[str], None] = "0e07c7d866ed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "charge_reminders",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("charge_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["charge_id"], ["charges.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("charge_id", "kind"),
    )
    op.create_index(
        op.f("ix_charge_reminders_charge_id"), "charge_reminders", ["charge_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_charge_reminders_charge_id"), table_name="charge_reminders")
    op.drop_table("charge_reminders")
    # ### end Alembic commands ###
