"""add lease_reminders

Revision ID: 5f2bdf7f2048
Revises: bbba6bd9608b
Create Date: 2026-07-21 18:37:34.354178

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5f2bdf7f2048"
down_revision: Union[str, Sequence[str], None] = "bbba6bd9608b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lease_reminders",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("lease_id", sa.Uuid(), nullable=False),
        sa.Column("threshold_days", sa.Integer(), nullable=False),
        sa.Column(
            "sent_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["lease_id"], ["leases.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("lease_id", "threshold_days"),
    )
    op.create_index(
        op.f("ix_lease_reminders_lease_id"), "lease_reminders", ["lease_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_lease_reminders_lease_id"), table_name="lease_reminders")
    op.drop_table("lease_reminders")
    # ### end Alembic commands ###
