"""add invitation lease_id and lease_tenants

Revision ID: bbba6bd9608b
Revises: b5d49658f834
Create Date: 2026-07-21 14:41:14.441046

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bbba6bd9608b"
down_revision: Union[str, Sequence[str], None] = "b5d49658f834"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lease_tenants",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("lease_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["lease_id"], ["leases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("lease_id", "user_id"),
    )
    op.create_index(op.f("ix_lease_tenants_lease_id"), "lease_tenants", ["lease_id"], unique=False)
    op.create_index(op.f("ix_lease_tenants_user_id"), "lease_tenants", ["user_id"], unique=False)
    op.add_column("invitations", sa.Column("lease_id", sa.Uuid(), nullable=True))
    op.create_index(op.f("ix_invitations_lease_id"), "invitations", ["lease_id"], unique=False)
    op.create_foreign_key(None, "invitations", "leases", ["lease_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Dropping the column also drops its (unnamed) foreign key constraint.
    op.drop_index(op.f("ix_invitations_lease_id"), table_name="invitations")
    op.drop_column("invitations", "lease_id")
    op.drop_index(op.f("ix_lease_tenants_user_id"), table_name="lease_tenants")
    op.drop_index(op.f("ix_lease_tenants_lease_id"), table_name="lease_tenants")
    op.drop_table("lease_tenants")
