"""add leases table

Revision ID: c261a7ef19ec
Revises: 11681eeccf15
Create Date: 2026-07-21 01:04:19.371040

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c261a7ef19ec"
down_revision: Union[str, Sequence[str], None] = "11681eeccf15"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "leases",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("property_id", sa.Uuid(), nullable=False),
        sa.Column("tenant_name", sa.String(length=255), nullable=False),
        sa.Column("tenant_email", sa.String(length=255), nullable=False),
        sa.Column("rent_amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "rent_frequency",
            sa.Enum("weekly", "fortnightly", "monthly", name="leasefrequency"),
            nullable=False,
        ),
        sa.Column("bond_amount", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("notice_period_days", sa.Integer(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["property_id"],
            ["properties.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_leases_organization_id"), "leases", ["organization_id"], unique=False)
    op.create_index(op.f("ix_leases_property_id"), "leases", ["property_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_leases_property_id"), table_name="leases")
    op.drop_index(op.f("ix_leases_organization_id"), table_name="leases")
    op.drop_table("leases")
    # Drop the enum type this migration created (op.drop_table leaves it behind).
    sa.Enum(name="leasefrequency").drop(op.get_bind())
    # ### end Alembic commands ###
