"""add properties table

Revision ID: c8f1fac2acbb
Revises: 40ced599e004
Create Date: 2026-07-20 00:32:35.548280

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c8f1fac2acbb"
down_revision: Union[str, Sequence[str], None] = "40ced599e004"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "properties",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("address", sa.String(length=500), nullable=False),
        sa.Column(
            "type",
            sa.Enum("apartment", "house", "condo", "townhouse", "other", name="propertytype"),
            nullable=False,
        ),
        sa.Column("bedrooms", sa.Integer(), nullable=False),
        sa.Column("bathrooms", sa.Integer(), nullable=False),
        sa.Column("parking", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(length=2000), nullable=True),
        sa.Column("status", sa.Enum("vacant", "occupied", name="propertystatus"), nullable=False),
        sa.Column("image_urls", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_properties_organization_id"), "properties", ["organization_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_properties_organization_id"), table_name="properties")
    op.drop_table("properties")
    # ### end Alembic commands ###
