"""drop properties.status

Revision ID: e3cae689b06e
Revises: c261a7ef19ec
Create Date: 2026-07-21 01:40:33.208285

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e3cae689b06e"
down_revision: Union[str, Sequence[str], None] = "c261a7ef19ec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("properties", "status")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Re-add the column referencing the existing enum type (create_type=False),
    # backfilling existing rows via a temporary server default, then drop the default.
    op.add_column(
        "properties",
        sa.Column(
            "status",
            postgresql.ENUM("vacant", "occupied", name="propertystatus", create_type=False),
            nullable=False,
            server_default="vacant",
        ),
    )
    op.alter_column("properties", "status", server_default=None)
